apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  namespace: login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: srevil/flask-app:latest
          env:
            - name: MYSQL_HOST
              value: mysql-service  # MySQL 서비스명
            - name: MYSQL_USER
              value: "admin"
            - name: MYSQL_PASSWORD
              value: "admin"
            - name: MYSQL_DB
              value: "user_db"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: login
spec:
  selector:
    app: flask-app
  ports:
    - port: 5000
      targetPort: 5000